version: '3.8'

networks:
  my-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  mongodata:

services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - my-network

  gafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - my-network

  ecommerce_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - product_api
      - users_api
    networks:
      - my-network

  product_api:
    build:
      context: ./product-api
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    networks:
      - my-network

  users_api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - my-network

