version: '3.8'

networks:
  my-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  mongodata:

services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - my-network
    ports:
      - "9090:9090"

  gafana:
    image: grafana/grafana:8.2.2
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    links:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - my-network

  ecommerce_api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./docker/ecommerce_api:ecommerce_api
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - prometheus
      - grafana
      - product_api
      - users_api
    networks:
      - my-network

  product_api:
    build:
      context: ./product-api
      dockerfile: Dockerfile
    volumes:
      - ./docker/product_api:product_api
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
      - prometheus
      - grafana
    networks:
      - my-network

  users_api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    volumes:
      - ./docker/users_api:users_api
    ports:
      - '8082:8082'
    depends_on:
      - mongodb
      - prometheus
      - grafana
    networks:
      - my-network

